# Uncomment the next line to define a global platform for your project
# platform :ios, '7.0'

target 'TestPods' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestPods

  pod 'AFNetworking'
  pod 'SDWebImage'
  #pod 'DataLayer’, :path => ‘./DataLayer/'

end
