# Uncomment the next line to define a global platform for your project
# platform :ios, '7.0'

target 'TestPods' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  
  source 'https://github.com/CocoaPods/Specs.git'
  source 'https://github.com/workhardupc/testcocoapodsSpecs.git'        #官方仓库地址

  # Pods for TestPods

  pod 'AFNetworking'
  pod 'SDWebImage'
  #pod 'DataLayer’, :path => ‘./DataLayer/'
  pod 'testcocoapods3'

end
